### ISSUE TITLE
New tag/release?

### ISSUE THREAD

**Issue by ivanpepelko** [php-school/workshop-manager#63]
Last tagged version was in 2016, which means that packages are severely outdated in 'latest stable version'.

This is most noticeable while installing with `composer global`, where having installed basically any other package means broken compatibility. By 'basically any' I mean a lot of packages that are installed with `composer global` depend on `symfony/console` - just an example from top of my head.

**Comment by AydinHassan** [comment]
Hi! We don't release `workshop-manager` via tags and we don't recommend to install via composer global require because of all the conflicting dependencies. Instead a phar is auto* built on commits to master and uploaded to the `gh-pages` branch which is available via `https://php-school.github.io/workshop-manager/workshop-manager.phar`

\* the auto build script is actually not running atm since the github actions migration from travis.

I can tag a release though, if you really would like, since it won't harm. Just wanted to communicate that's not the recommended way to install.

**Comment by ivanpepelko** [comment]
If that is the recommended way, then I must agree with you.

To further justify my way of thinking:
A friends wants to get into php development, and at this very moment I am guiding him trough installation process. Apart from php installation, there is also composer installation, then adding everything to $PATH, then workshop-manager, etc etc...
The point is - installing process is easy for someone experienced with php (ecosystem), but as I would guess, this project is aiming more towards newcomers.

Anyway, just disregard this issue if you do not plan to support installation over `composer global`. Consider this as a suggestion for the future.

PS. Just got screenshot from my friend, he is solving his first exercise! 🥳🥳🥳

**Comment by AydinHassan** [comment]
That's really great news! Thanks for letting us know.

We are totally up for making the process easier and initially we did recommend the composer global way, but then we had so many bug reports about conflicting deps since almost everything you might global require, depends on some symfony deps.

That was kinda the thought process behind bundling the phar and providing instructions there (via the verify command). Actually with the phar, you don't need composer. But with the global you do need composer and then you need to add composers bin dir to `$PATH` anyway.

Totally agree there is room for improvement and I'm happy to provide tags but I don't want to offer two ways to install because that will confuse users even more. If you have any more ideas please let us know 😄
